apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: node-app
  name: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: node-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: node-app
    spec:
      containers:
      - image: uqudo.azurecr.io/node-app
        name: node-app
        resources: {}
status: {}
